#!/usr/bin/env python3
# Author: Huy Tran
# Company: Cadence Design Systems Vietnam
# Email: huytran@cadence.com
# Created: 2026-09-27
"""Build self-contained dist/index.html and dist/parent.html that open by double-click (file://).

Browsers block ES-module imports and fetch() over file://, so this bundler:
  * inlines assets/app.css,
  * concatenates src/*.mjs in dependency order as ONE classic <script> (imports/exports stripped;
    the modules only use top-level `export function|const|class` and `import { .. } from './x.mjs'`),
  * embeds content/index.json, every PUBLISHED book, and their SVG/audio assets into window.__RO_BUNDLE__
    (src/ui.mjs reads it instead of fetch when present).
The dev layout (index.html + src/ + content/) is unchanged and still works over HTTP.

Usage: python3 tools/build_single_file.py        (writes dist/; run validate_content.py --index first)
"""
import base64
import json
import mimetypes
import os
import re
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
SRC, CONTENT, DIST = (os.path.join(ROOT, d) for d in ('src', 'content', 'dist'))
IMPORT_RE = re.compile(r"^import\s*\{[^}]*\}\s*from\s*'\./([\w-]+\.mjs)';\s*$", re.M)
EXPORT_RE = re.compile(r'^export\s+(?=(?:async\s+)?(?:function|class|const|let)\b)', re.M)


def read(p):
    with open(p, encoding='utf-8') as f:
        return f.read()


def module_order(entry):
    """Depth-first dependency order for the given entry module (deps before dependents)."""
    order, seen = [], set()

    def visit(name):
        if name in seen:
            return
        seen.add(name)
        for dep in IMPORT_RE.findall(read(os.path.join(SRC, name))):
            visit(dep)
        order.append(name)
    visit(entry)
    return order


def bundle_js(entry):
    parts = []
    for name in module_order(entry):
        src = read(os.path.join(SRC, name))
        if re.search(r'^export\s*\{', src, re.M) or re.search(r'^export\s+default', src, re.M):
            raise SystemExit(f'{name}: only `export function|const|class|let` is supported by this bundler')
        src = IMPORT_RE.sub('', src)
        src = EXPORT_RE.sub('', src)
        # Each module becomes its own block scope; shared names are hoisted via `globalThis` below.
        parts.append(f'// ---- {name}\n{src}')
    body = '\n'.join(parts)
    # Module-scope `const/let/function/class` collide across files only if names repeat; check that.
    names = re.findall(r'^(?:const|let|function|class|async function)\s+([A-Za-z_$][\w$]*)', body, re.M)
    dups = sorted({n for n in names if names.count(n) > 1})
    if dups:
        raise SystemExit('name collision across modules; rename before bundling: ' + ', '.join(dups))
    return '(() => {\n"use strict";\n' + body + '\n})();\n'


def bundle_content():
    idx = json.loads(read(os.path.join(CONTENT, 'index.json')))
    data = {'json': {'index.json': idx}, 'assets': {}}
    for b in idx['books']:
        data['json'][b['file']] = json.loads(read(os.path.join(CONTENT, b['file'])))
        for rel in b.get('assets', []):
            p = os.path.join(CONTENT, rel)
            if not os.path.isfile(p):
                continue  # validate_content already rejects broken paths for PUBLISHED books
            mime = mimetypes.guess_type(p)[0] or 'application/octet-stream'
            with open(p, 'rb') as f:
                data['assets'][rel] = f'data:{mime};base64,' + base64.b64encode(f.read()).decode('ascii')
    return data


def build_page(html_name, entry):
    html = read(os.path.join(ROOT, html_name))
    css = read(os.path.join(ROOT, 'assets', 'app.css'))
    js = bundle_js(entry)
    bundle_json = json.dumps(bundle_content(), ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/')
    html = html.replace('<link rel="stylesheet" href="assets/app.css">', '<style>\n' + css + '\n</style>')
    html = html.replace('  <link rel="manifest" href="manifest.webmanifest">\n', '')
    icon_path = os.path.join(ROOT, 'assets', 'icons', 'mascot.svg')
    if os.path.isfile(icon_path):
        with open(icon_path, 'rb') as f:
            icon_uri = 'data:image/svg+xml;base64,' + base64.b64encode(f.read()).decode('ascii')
        html = html.replace('href="assets/icons/mascot.svg"', f'href="{icon_uri}"')
    html = re.sub(r'<script type="module" src="src/[\w-]+\.mjs"></script>',
                  lambda m: '<script>window.__RO_BUNDLE__=' + bundle_json + ';</script>\n  <script>\n' + js.replace('</script', '<\\/script') + '</script>',
                  html)
    html = html.replace('<!--\nAuthor:', '<!--\nGENERATED by tools/build_single_file.py - edit the sources in src/, assets/, content/ instead.\nAuthor:', 1)
    os.makedirs(DIST, exist_ok=True)
    out = os.path.join(DIST, html_name)
    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        f.write(html)
    return out, len(html)


def main():
    if not os.path.isfile(os.path.join(CONTENT, 'index.json')):
        raise SystemExit('content/index.json missing: run python3 tools/validate_content.py --index first')
    for page, entry in (('index.html', 'kid-app.mjs'), ('parent.html', 'parent-dashboard.mjs')):
        out, n = build_page(page, entry)
        print(f'wrote {os.path.relpath(out, ROOT)} ({n / 1024:.0f} KB)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
